name: Maven CI

on:
  push: { branches: [master] }
  pull_request: { branches: [master] }

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: set up temurin JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven
    - name: build & Test
      run: mvn clean verify